name: Changelog Tracking
run-name: Changelog Tracking
on: [push]
jobs:
  track:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.16.0
      - id: changedfiles
        name: Get changed files
        uses: collin-miller/git-changesets@v1
        with:
          format: json
      - name: Parse changed files
        id: parsedfiles
        uses: rjt-rockx/changelog-action@main
        with:
          files: ${{ steps.changedfiles.outputs.added_modified }}
          filter: "changelogs/(.*).md"
      - name: Get latest tag
        id: latesttag
        if: ${{ steps.parsedfiles.latest }}
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          fallback: ${{ steps.parsedfiles.latest }}
      - name: Create Github release
        uses: softprops/action-gh-release@v0.1.14
        if: ${{ success() && steps.latesttag.tag != steps.parsedfiles.latest }}
        with:
          body: ${{ steps.parsedfiles.content }}
          generate_release_notes: false
      - name: Post to Discord webhook
        uses: tsickert/discord-webhook@v5.3.0
        if: ${{ success() && steps.parsedfiles.latest }}
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          username: Hyperbeam
          embed-title: Changelog ${{ steps.parsedfiles.latest }}
          embed-description: ${{ steps.parsedfiles.content }}
